package es.upv.indigodc.service.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * The information about a deployment managed by A4C.
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class A4cOrchestratorInfo {

    /**
     * The deployment PaaS ID as given by A4C.
     */
    protected String deploymentPaasId;
    /**
     * The deployment ID as generated by A4C.
     */
    protected String deploymentId;
    /**
     * The list of locations for the current deployment.
     */
    protected String[] locationIds;
    /**
     * The ID of the orchestrator that manages thois deployment.
     */
    protected String orchestratorId;
    /**
     * The ID of the version of the deployed topology.
     */
    protected String versionId;
}
