package es.upv.indigodc.service.model;

import alien4cloud.paas.model.DeploymentStatus;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Maintain the relation between the id of the deployment and its status.
 *
 * @author asalic
 */
@Getter
@AllArgsConstructor
public class OrchestratorDeploymentMapping {
  public static final OrchestratorDeploymentMapping EMPTY =
      new OrchestratorDeploymentMapping("unknown_deployment_id", DeploymentStatus.UNKNOWN);

  /**
   * The id of the deployment as generated by the orchestrator. This id is returned by the
   * orchestrator when a deployment has successfully been executed.
   */
  private String orchestratorUuidDeployment;
  /** The status of the deployment. */
  private DeploymentStatus status;
}
